const prompts = [
  "Day and night",
  "Futurism",
  "Archeology",
  "Life & Growth",
  "Death & Decay",
  "Loud",
  "The pixel.",
  "Capital R Romantic",
  "Heartbeat",
  "Games are art and you cannot let anyone tell you otherwise",
  "Elemental",
  "Be small, do crimes",
  "A chain of blocks but NOT blockchain okay? Idk man figure it out",
  "Under construction",
  "Delicious",
  "Spirit week (like, with regard to ghosts. Also it’s still just one day)",
  "Decades day",
  "A dog with a stick",
  "Tiny",
  "Invasive species",
  "Pick a piece of non-digital art and reference it, but I swear if it’s Mondrian you’re gonna get a bonk.",
  "Justice",
  "I love mess",
  "You ever think about like, your regrets in life?",
  "Automaton",
  "Memphis to Miami",
  "Dot dot dot",
  "Language arts",
  "Just vibes",
  "ActuallyGoodFinal_final-v2.png",
  "WILD CARD HALLOWEEN"
]

module.exports = prompts;